name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: yarn blueprint build
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ${{ env.main_project_module }}/build/